### ISSUE TITLE
Progress and colors are broken

### ISSUE THREAD

**Issue by itonics-tbeauvais** [Cosium/dry-dry#10]
See the screenshot.

When I run `npm` the WARN is colored and when I run `dry` it is not. This goes for all colored statements. This is just an example. Disregard the different warning statements.

<img width="846" alt="screen shot 2018-05-31 at 12 59 01" src="https://user-images.githubusercontent.com/9199882/40767570-9d4c8240-64d2-11e8-9a9d-d45060ec71c7.png">

Also, there are no progress logs from npm.

**Comment by reda-alaoui** [comment]
Fixed by #14
