### ISSUE TITLE
Using Dry to save dependencies

### ISSUE THREAD

**Issue by itonics-tbeauvais** [Cosium/dry-dry#15]
As a developer, I am wanting to use Dry to use some of the basic mutations to update the package-dry.json such as added dependencies (which might be the only one).

```
dry i -S typedi
```

Right now, Dry is nothing taking this and putting it in the current directories package-dry.json yet to the merge.json. This is a pain since I have to cut and paste it from the package.json.

**Comment by treilhes** [comment]
Leave a comment

**Comment by treilhes** [comment]
Solved, no reply after a week, so closing
