### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by dolanmiu** [Cosium/dry-dry#2]
So happy this project exists by the way

We need this exact tool

Can we enable Travis CI on this project?

**Comment by reda-alaoui** [comment]
Yes good idea.
Can you write the travis file?

**Comment by dolanmiu** [comment]
Yes I can, give me a few minutes

**Comment by dolanmiu** [comment]
https://github.com/Cosium/dry-dry/pull/3

**Comment by reda-alaoui** [comment]
Fixed in https://github.com/Cosium/dry-dry/commit/935930555581a6b8dbc9d37a119b4045781dc646
