### ISSUE TITLE
fs-extra typings

### ISSUE THREAD

**Issue by dolanmiu** [Cosium/dry-dry#4]
fs-extra has typings:

https://www.npmjs.com/package/@types/fs-extra

So what is this for?

https://github.com/Cosium/dry-dry/blob/master/src/typings.d.ts#L1

**Comment by reda-alaoui** [comment]
Hum, I don't remember.
I suppose I didn't look for a typing lib.

If `@types/fs-extra` can do the same job, it is indeed better to use it ;)

**Comment by reda-alaoui** [comment]
Fixed by #7
