### ISSUE TITLE
FR - Parameterize package manager command (Support Yarn)

### ISSUE THREAD

**Issue by zmoshansky** [Cosium/dry-dry#8]
Thanks for creating this package, I found it via https://github.com/npm/npm/issues/8112 and it looks to be the most tenable solution to our problems as well!

Would you be open to a PR parameterizing the exec calls of this package to be configurable for non-npm workflows?

Something along these lines...

```
export interface DryPackageDescriptor {
    extends?: string;
    dependencies?: DryDependencies;


   /**
    * Package manager command; Defaults to `npm`. 
    * Useful for configuring alternative build tools
    */
    packageManager?: 'npm' | 'yarn';
}
```

**Comment by reda-alaoui** [comment]
Hello Zachary,

That's a great idea.
Waiting for your PR :)
