### ISSUE TITLE
Parent Resolution Bug

### ISSUE THREAD

**Issue by ngiebel** [Cosium/dry-dry#9]
If a parent is attempted to be extended in any form, either using a relative path or node_module path to a dry file it fails to resolve it and causes an overall silent command failure.

The issue appears to be the use of `require` at 
https://github.com/Cosium/dry-dry/blob/master/src/dry-package.ts#L108

It attempts to resolve at the global install location of `dry-dry` but the dependency was installed at the context of shell location that invoked the `dry` command. I can sort of work around it by locally installing `dry-dry` and executing something along the lines of `node path_to_dry-dry/index.js run someScriptName` but that is not going to work overall. 

Another issue exists too, if following the example dependencies declaration format:
```JSON
    "dependencies": {
      "parent": "1.0.0"
    }
```
`dry-dry` will attempt to execute the command `npm install --no-save 1.0.0`; it appears due to the conditional at https://github.com/Cosium/dry-dry/blob/master/src/dependency-resolver.ts#L23.

**Comment by reda-alaoui** [comment]
Hello @ngiebel ,
Can I clone some repository to reproduce the issue?

**Comment by treilhes** [comment]
Hello @ngiebel , @reda-alaoui ,
Please see Pull request #12
